### ISSUE TITLE
Importing modules in B dynamic module (compiled by otf)

### ISSUE THREAD

**Issue by job-so** [maximusk/Here-is-what-you-need-to-know-about-dynamic-components-in-Angular#1]
Hi Maximusk,

__First many thanks for your articles and knowledge sharing.__
FYI, my final goal is to use an otf component recursively.

But, i am first struggled with a basic (and static) component import in the dynamic module.

[Diff in my fork] (https://github.com/job-so/Here-is-what-you-need-to-know-about-dynamic-components-in-Angular/commit/3a3d4ea423d09e67d38490edacb8dc2c4d485f1d)

The new C component template is totally replacing the B component template (there is no C component tag anywhere in templates)

![image](https://user-images.githubusercontent.com/15981454/28956337-874569b2-78ec-11e7-990b-65c95915db7f.png)

Do you have any ideas / recommendations ?

Thank you

**Comment by maximusk** [comment]
If I understood you correctly you expect to see a string `I am B component` instead of `I am C component imported by dynamic B component`. For that you need to take the correct factory here:

`const f = factories.componentFactories[0];`

I used index `0` in my example because the `tmpModule` contained only one component. Once you imported `CModule` it now contains two components, so you need to take the second factory:

`const f = factories.componentFactories[0];`

Actually, the better approach would be to use factoryResolver to get the correct factory:

```
    ngAfterViewInit() {
        const template = '<span>I am {{name}}</span>';

        const tmpCmp = Component({template: template})(class {
        });
        const tmpModule = NgModule({imports: [CModule], declarations: [tmpCmp], entryComponents: [tmpCmp]})(class {
        });

        this._compiler.compileModuleAsync(tmpModule)
            .then((moduleFactory) => {
                const resolver = moduleFactory.create(this._injector).componentFactoryResolver;
                const f = resolver.resolveComponentFactory(tmpCmp);
                // const f = resolver.resolveComponentFactory(CComponent);
                const cmpRef = f.create(this._injector, [], null, this._m);
                cmpRef.instance.name = 'B component';
                this._container.insert(cmpRef.hostView);
            })
    }
```

**Comment by job-so** [comment]
__Brilliant !!!__
This is exactly what I need.
Many thanks.

**Comment by maximusk** [comment]
You're welcome, good luck)
